### Get all transactions
GET http://localhost:3001/transactions

###
GET http://localhost:3001/transactions?transactionId=100234

###
GET http://localhost:3001/transactions?credited=true

###
GET http://localhost:3001/transactions?passageType=NoAgreement_FreeFlow

###
GET http://localhost:3001/transactions?lpn.number_like=ABC

###

GET http://localhost:3001/transactions?_page=1&_limit=10